version = 0.1

[default.deploy.parameters]
stack_name = "dining-concierge"
resolve_s3 = true
s3_prefix = "dining-concierge"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
