SAMPLE_RESTAURANTS = [
    {
        "name": "Juniper Table",
        "cuisine": "American",
        "location": "Manhattan",
        "rating": 4.7,
        "address": "21 W 18th St, New York, NY",
    },
    {
        "name": "Saffron House",
        "cuisine": "Indian",
        "location": "Manhattan",
        "rating": 4.8,
        "address": "118 Lexington Ave, New York, NY",
    },
    {
        "name": "Curry Leaf Brooklyn",
        "cuisine": "Indian",
        "location": "Brooklyn",
        "rating": 4.6,
        "address": "73 Atlantic Ave, Brooklyn, NY",
    },
    {
        "name": "Tokyo Alley",
        "cuisine": "Japanese",
        "location": "Manhattan",
        "rating": 4.7,
        "address": "14 E 13th St, New York, NY",
    },
    {
        "name": "Sushi Harbor",
        "cuisine": "Japanese",
        "location": "Brooklyn",
        "rating": 4.5,
        "address": "215 Court St, Brooklyn, NY",
    },
    {
        "name": "Casa Verde",
        "cuisine": "Mexican",
        "location": "Queens",
        "rating": 4.7,
        "address": "31-18 30th Ave, Astoria, NY",
    },
    {
        "name": "Nonna's Corner",
        "cuisine": "Italian",
        "location": "Manhattan",
        "rating": 4.6,
        "address": "83 Thompson St, New York, NY",
    },
    {
        "name": "Basil & Stone",
        "cuisine": "Mediterranean",
        "location": "Brooklyn",
        "rating": 4.8,
        "address": "190 Bedford Ave, Brooklyn, NY",
    },
    {
        "name": "Bangkok Night Market",
        "cuisine": "Thai",
        "location": "Queens",
        "rating": 4.6,
        "address": "71-22 Roosevelt Ave, Jackson Heights, NY",
    },
    {
        "name": "Seoul Kitchen",
        "cuisine": "Korean",
        "location": "Manhattan",
        "rating": 4.8,
        "address": "12 W 32nd St, New York, NY",
    },
]
